/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.llevett

import spock.lang.Specification

class WordUtilTest extends Specification {
    def "word util counts words"() {
        setup:
        def phrase = 'This is a test. Is this a good test? Maybe not.'

        when:
        def result = WordUtil.countWords(phrase)

		then:
        ! result.isEmpty()
		result['good'] == 1
		result['test'] == 2
		result['not'] == 1
		result['this'] == 2
    }

	def "count occurrences returns 0 for words not found"() {
		setup:
		def phrase = 'This is a test. Is this a good test? Maybe not.'
		def searches = ['bad', 'missing'] as String[]

		when:
		def result = WordUtil.countOccurrences(phrase, searches)

		then:
		! result.isEmpty()
		result['test'] == 2
		searches.each {
			result[it] == 0
		}
	}

	def "group words by first letter"() {
		setup:
		def phrase = 'This is a test. Is this a good test? Maybe not.'

		when:
		def result = WordUtil.groupByFirstLetter(phrase)

		then:
		! result.isEmpty()
		result['t'].containsAll(['this', 'test'])
	}
}
